name: test & lint

on:
  push:

jobs:
  testing:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
      - name: Checkout Repository
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Set up Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: 25
          cache: "npm"
      - name: Install dependencies
        run: npm install --force --include=dev
      - name: Set up environment variables
        run: |
          echo "COOKIE_NAME=placemark" >> .env
          echo "COOKIE_PASSWORD=${{ secrets.COOKIE_PASSWORD }}" >> .env
          echo "GITHUB_CLIENT_ID=${{ secrets.AUTH_GITHUB_CLIENT_ID }}" >> .env
          echo "GITHUB_CLIENT_SECRET=${{ secrets.AUTH_GITHUB_CLIENT_SECRET }}" >> .env
          echo "HOSTNAME=localhost" >> .env
          echo "PORT=3000" >> .env
          echo "DB=mongodb://localhost/placemark" >> .env
      - name: Run lint
        run: npm run lint
      - name: Start the app
        run: nohup npm run start &
      - name: Run e2e tests
        uses: cypress-io/github-action@2ad32e649e4db26c07674ebae31a297601dbcbaf # v6.10.8
        with:
          browser: firefox
          install: false
          wait-on: http://localhost:3000
          wait-on-timeout: 30000
      - name: Run tests
        run: npm run test
